export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR'
export const INFINITE_LOADING_START = 'INFINITE_LOADING_START'

export const FETCH_LATEST_NEWS_REQUEST = 'FETCH_LATEST_NEWS_REQUEST'
export const FETCH_LATEST_NEWS_SUCCESS = 'FETCH_LATEST_NEWS_SUCCESS'
export const FETCH_LATEST_NEWS_ERROR = 'FETCH_LATEST_NEWS_ERROR'

export const FETCH_SIDE_BAR_TOP_NEWS_REQUEST = 'FETCH_SIDE_BAR_NEWS_REQUEST'
export const FETCH_SIDE_BAR_TOP_NEWS_SUCCESS = 'FETCH_SIDE_BAR_NEWS_SUCCESS'
export const FETCH_SIDE_BAR_TOP_NEWS_ERROR = 'FETCH_SIDE_BAR_NEWS_ERROR'

export const FETCH_SIDE_BAR_FEATURED_NEWS_REQUEST = 'FETCH_SIDE_BAR_FEATURED_NEWS_REQUEST'
export const FETCH_SIDE_BAR_FEATURED_NEWS_SUCCESS = 'FETCH_SIDE_BAR_FEATURED_NEWS_SUCCESS'
export const FETCH_SIDE_BAR_FEATURED_NEWS_ERROR = 'FETCH_SIDE_BAR_FEATURED_NEWS_ERROR'

export const FETCH_SEARCH_NEWS_REQUEST = 'FETCH_SEARCH_NEWS_REQUEST'
export const FETCH_SEARCH_NEWS_SUCCESS = 'FETCH_SEARCH_NEWS_SUCCESS'
export const FETCH_SEARCH_NEWS_ERROR = 'FETCH_SEARCH_NEWS_ERROR'

export const ENABLE_HEADER_STICKY = 'ENABLE_HEADER_STICKY'
export const DISABLE_HEADER_STICKY = 'DISABLE_HEADER_STICKY'
